"""Lower FIFO transport to streamed input and independently released output BDs.

The MemTile joins, Shim DDR patches, input BDs and all initial lock values
stay those generated by IRON. Fail on any unexpected
lowered spelling or lock assignment rather than guessing operation indices.
"""
import re


def stream_input(module: str, cores: int) -> str:
    """Give C++ ownership of input locks across a full channel reduction.

    The IRON bootstrap is a placement/route template, never runnable. Its
    three-pointer call is replaced by a four-pointer ABI in this final module.
    DMA BDs and Shim DDR patch offsets remain generated by the compiler.
    """
    signature = 'memref<3264xi8>, memref<256xi8>, memref<960xi8>'
    module, count = re.subn(r'(func.func private @conv2d_\w+\()' + re.escape(signature) + r'\)',
                           r'\g<1>' + signature + ', memref<3264xi8>)', module)
    if count != 1:
        raise ValueError('Expected one streaming kernel declaration')
    for col in range(4 if cores == 16 else 1):
        for row in range(4 if cores == 16 else 1):
            ip = f'%input_c{col}_split{row}_cons'
            op = f'%output_c{col}_join{row}'
            for suffix, lock, initial in (('prod', 2, 2), ('cons', 3, 0)):
                pattern = (rf'{ip}_{suffix}_lock_0 = aie.lock\(%tile_{col}_{row+2}, {lock}\) '
                           rf'\{{init = {initial} : i32,')
                if not re.search(pattern, module):
                    raise ValueError(f'Unexpected streaming lock ABI: {ip}')
            for index, address in enumerate((1024, 32768)):
                pattern = rf'({ip}_buff_{index} = aie.buffer\([^\n]+\) \{{)address = \d+ : i32, mem_bank = \d+ : i32,'
                module, count = re.subn(pattern, rf'\g<1>address = {address} : i32, mem_bank = {address // 16384} : i32,', module)
                if count != 1:
                    raise ValueError('Expected two explicitly placed input buffers')
            # Separate ping, activation, pong and output across all four banks.
            pattern = rf'({op}_buff_0 = aie.buffer\([^\n]+\) \{{)address = \d+ : i32, mem_bank = \d+ : i32,'
            module, count = re.subn(pattern, r'\g<1>address = 49152 : i32, mem_bank = 3 : i32,', module)
            if count != 1:
                raise ValueError('Expected one core output buffer')
            pattern = (rf'(?P<open>    %core_{col}_{row+2} = aie.core\(%tile_{col}_{row+2}\) \{{)\n'
                       r'.*?\n    \} \{link_files = \["(?P<symbol>conv2d_\w+)\.o"\]\}')
            match = re.search(pattern, module, re.S)
            if match is None:
                raise ValueError('Expected lowered core body')
            body = f'''{match['open']}
      %c1_i32 = arith.constant 1 : i32
      cf.br ^run
    ^run:
      aie.use_lock({op}_prod_lock_0, AcquireGreaterEqual, %c1_i32)
      func.call @{match['symbol']}({ip}_buff_0, {op}_buff_0, %activations_{col}_{row}, {ip}_buff_1) : ({signature}, memref<3264xi8>) -> ()
      aie.use_lock({op}_cons_lock_0, Release, %c1_i32)
      cf.br ^run
    }} {{link_files = ["{match['symbol']}.o"]}}'''
            module = module[:match.start()] + body + module[match.end():]
    return module


def chunk_output(module: str, cores: int) -> str:
    for col in range(4 if cores == 16 else 1):
        for row in range(4 if cores == 16 else 1):
            prefix = f'output_c{col}_join{row}'
            ready, free, buffer = (f'%{prefix}_cons_lock_0', f'%{prefix}_prod_lock_0', f'%{prefix}_buff_0')
            lock_line = re.search(rf'{re.escape(ready)} = aie.lock\(%tile_{col}_{row+2}, (\d+)\)', module)
            if lock_line is None or lock_line[1] != '1':
                raise ValueError('C++ output-ready lock ID must be exactly 1 on every core')
            # This is the core producer's old whole-buffer publication. The
            # C++ function now publishes one credit after each 64-byte store.
            release_pattern = rf'^\s*aie.use_lock\({re.escape(ready)}, Release, %c1_i32\).*\n'
            module, count = re.subn(release_pattern, '', module, flags=re.M)
            if count != 1:
                raise ValueError(f'Expected exactly one core publication for {prefix}')
            pattern = (rf'(?P<indent> +)aie.use_lock\({re.escape(ready)}, AcquireGreaterEqual, (?P<one>%\w+)\)[^\n]*\n'
                       rf' +aie.dma_bd\({re.escape(buffer)} : memref<256xi8> offset = 0 len = 256\)[^\n]*\n'
                       rf' +aie.use_lock\({re.escape(free)}, Release, (?P=one)\)[^\n]*\n'
                       r' +aie.next_bd \^(?P<label>\w+)[^\n]*')
            match = re.search(pattern, module)
            if match is None:
                raise ValueError(f'Expected core egress BD for {prefix}')
            indent, one, start = match['indent'], match['one'], match['label']
            first_id = int(re.search(r'bd_id = (\d+)', match[0])[1])
            lines = []
            for chunk in range(4):
                if chunk:
                    lines.append(f'    ^epilogue_chunk{chunk}:')
                lines.append(f'{indent}aie.use_lock({ready}, AcquireGreaterEqual, {one})')
                next_id = first_id + chunk + 1 if chunk < 3 else first_id
                lines.append(f'{indent}aie.dma_bd({buffer} : memref<256xi8> offset = {64*chunk} len = 64) '
                             f'{{bd_id = {first_id+chunk} : i32, next_bd_id = {next_id} : i32}}')
                if chunk == 3:
                    lines.append(f'{indent}aie.use_lock({free}, Release, {one})')
                else:
                    # The CDO emitter requires a release field on every BD.
                    # A zero increment preserves ownership until the last BD.
                    lines.append(f'{indent}%no_credit{chunk} = arith.constant 0 : i32')
                    lines.append(f'{indent}aie.use_lock({free}, Release, %no_credit{chunk})')
                next_label = f'epilogue_chunk{chunk+1}' if chunk < 3 else start
                lines.append(f'{indent}aie.next_bd ^{next_label}')
            module = module[:match.start()] + '\n'.join(lines) + module[match.end():]
    return module
